vim.keymap.set('n', '<Leader>flr', ':FlutterRun<CR>', {noremap = true})
vim.keymap.set('n', '<Leader>flhr', ':CocCommand flutter.dev.hotRestart<CR>', {noremap = true})
vim.keymap.set('n', '<Leader>flq', ':FlutterQuit<CR>', {noremap = true})
vim.keymap.set('n', '<Leader>fld', ':FlutterDevices<CR>', {noremap = true})
vim.keymap.set('n', '<Leader>fle', ':FlutterEmulators<CR>', {noremap = true})
--vim.keymap.set('n', '<Leader>flb', ':CocCommand flutter.dev.debugDumpAPP<CR>', {noremap = true})
